# Generated by Django 3.0.7 on 2021-03-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
