# Generated by Django 3.0.7 on 2021-03-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0003_tag_taxonomy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('taxonomy', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
